name: Upload binary
description: Uploads a compiled binary
inputs:
  SOURCE_FILE:
    description: 'Path to file to upload'
    required: true
    type: string
  DEST_NAME:
    description: 'Name to use for the uploaded artifact'
    required: true
    type: string
  DELETE_PERIOD:
    description: 'Auto delete uploaded artifact after X days'
    required: false
    default: 90
    type: string
runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.DEST_NAME }}
        path: ${{ inputs.SOURCE_FILE }}
        retention-days: ${{ inputs.DELETE_PERIOD }}
